# GitHub Dependabot Configuration
version: 2
updates:
  # Enable dependency updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable updates for GitHub Actions workflows (if using CI/CD)
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"