github: [nexoscreator, nexoscreation, nexoscrating]
# patreon: your-patreon-username
# open_collective: your-open-collective-username
# ko_fi: your-kofi-username
paypal: noscreator
# buymeacoffee: your-buymeacoffee-username
custom: [https://www.paypal.me/noscreator]