github: [nexoscreator, nexoscreation, nexoscrating]
# patreon: your-patreon-username
# open_collective: your-open-collective-username
# ko_fi: your-kofi-username
paypal: nexoscreator
# buymeacoffee: your-buymeacoffee-username
tidelift: npm/lazy-youtube-manager
custom: ["https://www.paypal.me/noscreator", nexoscreator.tech]